### ISSUE TITLE
Broken install header?

### ISSUE THREAD

**Issue by AntoinePrv** [lgottwald/PaPILO#28]
Hello,

After installing PaPILO with CMake, the program
```cpp
#include <papilo/core/Problem.hpp>

int main() {
    papilo::Problem<float> prob;
}
```
Fails with
```
include/papilo/core/SparseStorage.hpp:29:10: fatal error: pdqsort/pdqsort.h: No such file or directory
 #include "pdqsort/pdqsort.h"
```
Due to external header being installed under `include/papilo-external/pdqsort`
https://github.com/lgottwald/PaPILO/blob/894525d3402c2050909786680ddc4e2cbf1385bb/CMakeLists.txt#L335

Is this the desired behavior? Or is`papilo/core/Problem.hpp` a private header?

Thanks

**Comment by lgottwald** [comment]
Hi,

the behavior is somewhat desired. I did not want to install the external library headers that are shipped with PaPILO into the subfolder `papilo/` which is why they go into `papilo-external/`. For building from an installation and from source this requires different include directories to be added. For a standard installation one would need to add  `/usr/local/include/papilo-external/` in addition to `/usr/local/include/papilo`.

If you use CMake, however, the `find_package(PAPILO)` should handle all those differences automatically and you just link the `${PAPILO_IMPORTED_TARGETS}` cmake variable.

I am open to any suggestions on improving the usability of PaPILO in that regard though.

Leona

**Comment by AntoinePrv** [comment]
Thank you for the quick reply! That makes sense. My `CMakeLists.txt` was
```cmake
find_package(PAPILO REQUIRED)
add_executable(papilo-test papilo-test.cpp)
target_link_libraries(papilo-test PUBLIC libpapilo)
```
I replaced the libraries with
```cmake
target_link_libraries(papilo-test PUBLIC ${PAPILO_IMPORTED_TARGETS})
```
And it solved the issues.

Thank you for the help!
