### ISSUE TITLE
libpapilo-core.a not installed

### ISSUE THREAD

**Issue by AntoinePrv** [lgottwald/PaPILO#29]
Hello,

After installing with CMake in a custom location, I cannot see `libpapilo-core.a` under `lib`, only `libclusol.a`.
Is this the desired behavior? Or is `libpapilo-core.a` only an intermediate library not supposed to be installed?

Thanks

**Comment by lgottwald** [comment]
The libpapilo-core.a can be installed in principle but is not needed. It includes some precompiled template instantiations but requires to add the definition PAPILO_USE_EXTERN_TEMPLATES when using the header files. Because of C++ compiler compatibilities I decided against installing it and only use the libpapilo-core.a library for building the other binaries of papilo. The installation of PaPILO currently only includes the header files and static external libraries required to build with the enabled features, e.g. the libclusol.a which is used for the detection of linearly dependent rows and transitively passed downwards in the link chain by CMake.

**Comment by AntoinePrv** [comment]
Thanks for the clarification! Closing the issue then
